# Generated by Django 4.2.15 on 2024-08-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contact_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='ContactGroup',
        ),
    ]
