# Generated by Django 4.2.15 on 2024-08-25 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_groups_contactgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='creator',
            field=models.ForeignKey(default='MQT81BTRUG', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=1024)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
