# Generated by Django 4.2.15 on 2024-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactgroup_creator_emailcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgroup',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='api.contact'),
        ),
    ]
